sudo: required
language: bash
services:
  - docker
script:
  - docker-compose build processor-iconv
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true  
